#!/bin/bash

CURDIR=$(dirname $0);

noop()
{
  printf -- '';
}

ARG="$@";
CMD="$1";

case $CMD in
  'build')
    ${CURDIR}/$@;
    exit 0;
  ;;
  'test')
    ${CURDIR}/$@;
    exit 0;
  ;;
  'init')
    ${CURDIR}/$@;
    exit 0;
  ;;
  'shell')
    ${CURDIR}/$@;
    exit;
  ;;
  'start')
    ${CURDIR}/$@;
    exit 0;
  ;;
  'help')
    noop;
  ;&
  *)
    ${CURDIR}/help;
  ;;
esac;
