#!/bin/bash
noop()
{
  printf -- '';
}

add_gitignore()
{
  printf -- 'Add .gitignore? [y/N] ';
  read YESNO;
  case $YESNO in
    'yes')
      noop;
    ;&
    'y')
      noop;
    ;&
    'Y')
      noop;
    ;&
    '1')
      printf -- "vendor\napp\n*.out" > $(pwd)/.gitignore;
      printf -- '.gitignore has been setup.\n\n';
    ;;
  esac;
}

add_git()
{
  printf -- "Initialize git repository at $(pwd)? [y/N] ";
  read YESNO;
  case $YESNO in
    'yes')
      noop;
    ;&
    'y')
      noop;
    ;&
    'Y')
      noop;
    ;&
    '1')
      git init;
      printf -- 'Git repository setup done.\n\n';
      add_gitignore;
    ;;
  esac;
}

add_go_mod()
{
  printf -- 'Setup Go modules? [y/N] ';
  read YESNO;
  case $YESNO in
    'yes')
      noop;
    ;&
    'y')
      noop;
    ;&
    'Y')
      noop;
    ;&
    '1')
      GO111MODULE=on go mod init;
      printf -- 'Go mod set up successfully.\n\n';
    ;;
  esac;
}

add_dockerfile()
{
  printf -- 'Seed a Dockerfile? [y/N] ';
  read YESNO;
  case $YESNO in
    'yes')
      noop;
    ;&
    'y')
      noop;
    ;&
    'Y')
      noop;
    ;&
    '1')
      cat << 'EOF' > $(pwd)/Dockerfile
FROM zephinzer/golang-dev:latest as development
COPY . /go/src/app
ENTRYPOINT [ "start" ]

FROM development as build
RUN build
ENTRYPOINT [ "/go/src/app/app" ]

FROM scratch as production
COPY --from=build /go/src/app/app /
ENTRYPOINT [ "/app" ]
EOF
    ;;
  esac;
}

add_main_go()
{
  printf -- 'Seed a main.go? [y/N] ';
  read YESNO;
  case $YESNO in
    'yes')
      noop;
    ;&
    'y')
      noop;
    ;&
    'Y')
      noop;
    ;&
    '1')
      cat << 'EOF' > $(pwd)/main.go
package main

import (
  "fmt"
)

func main() {
  fmt.Println("hello world")
}
EOF
    ;;
  esac;
}

printf -- 'Checking for git setup... ';
git status &>/dev/null;
if [ "$?" != "0" ]; then
  printf -- 'Git setup not found!\n';
  add_git;
else
  printf -- 'Git setup found!\n';
fi;

git status &>/dev/null;
if [ "$?" = "0" ]; then
  printf -- "Checking for .gitignore... ";
  ls $(pwd)/.gitignore &>/dev/null;
  if [ "$?" != "0" ]; then
    printf -- '.gitignore not found!\n';
    add_gitignore;
  else
    printf -- '.gitignore found!\n';
  fi;
fi;

printf -- 'Checking for go mod... ';
ls $(pwd)/go.mod &>/dev/null;
if [ "$?" != "0" ]; then
  printf -- 'go.mod not found!\n';
  add_go_mod;
else
  printf -- 'go.mod found!\n\n';
fi;

printf -- 'Checking for Dockerfile... ';
ls $(pwd)/Dockerfile &>/dev/null;
if [ "$?" != " 0" ]; then
  printf -- 'Dockerfile not found!\n';
  add_dockerfile;
else
  printf -- 'Dockerfile found!\n\n';
fi;

printf -- 'Checking for main.go... ';
ls $(pwd)/main.go &>/dev/null;
if [ "$?" != " 0" ]; then
  printf -- 'main.go not found!\n';
  add_main_go;
else
  printf -- 'main.go found!\n\n';
fi;

printf -- "You're all set up!\n\n";

printf -- "- run 'make start' now to start developing!\n\n";
